language: objective-c
#osx_image: xcode7.3
osx_image: xcode8
xcode_workspace: ClockView.xcworkspace
xcode_scheme: ClockView
xcode_sdk: iphonesimulator
#before_install:
#  - gem install xcpretty
before_script:
  - set -eu -o pipefail
script:
  - uname -a
  - xcodebuild -workspace ClockView.xcworkspace -scheme ClockView -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' build test | xcpretty -c
